import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        // Pending expenses (12 total)
        {
            employeeId: 3,
            companyId: 1,
            amount: 1250.00,
            currency: 'USD',
            convertedAmount: 1250.00,
            category: 'Travel',
            description: 'Flight tickets for client meeting in Chicago',
            expenseDate: new Date('2024-11-15').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 2,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_001_flight_receipt.pdf',
            ocrData: { vendor: 'American Airlines', total: 1250.00, date: '2024-11-15', items: ['Flight AA1234: ORD-LAX'] },
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            employeeId: 4,
            companyId: 1,
            amount: 89.50,
            currency: 'USD',
            convertedAmount: 89.50,
            category: 'Office Supplies',
            description: 'Wireless keyboard and mouse for workstation',
            expenseDate: new Date('2024-11-20').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 2,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_002_office_supplies.jpg',
            ocrData: { vendor: 'Best Buy', total: 89.50, date: '2024-11-20', items: ['Logitech MX Keys', 'Logitech MX Master 3'] },
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            employeeId: 5,
            companyId: 1,
            amount: 65.75,
            currency: 'USD',
            convertedAmount: 65.75,
            category: 'Meals',
            description: 'Team lunch at Italian restaurant',
            expenseDate: new Date('2024-11-18').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 2,
            currentApprovalStep: 1,
            receiptUrl: null,
            ocrData: null,
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            employeeId: 8,
            companyId: 2,
            amount: 45.60,
            currency: 'EUR',
            convertedAmount: 49.65,
            category: 'Transportation',
            description: 'Taxi to airport for business trip',
            expenseDate: new Date('2024-11-12').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 7,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_004_taxi_receipt.jpg',
            ocrData: { vendor: 'Taxi Service Berlin', total: 45.60, date: '2024-11-12', items: ['Airport transfer'] },
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            employeeId: 9,
            companyId: 2,
            amount: 299.00,
            currency: 'EUR',
            convertedAmount: 325.48,
            category: 'Training',
            description: 'AWS Cloud Practitioner certification exam',
            expenseDate: new Date('2024-10-28').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 7,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_005_aws_cert.pdf',
            ocrData: { vendor: 'Amazon Web Services', total: 299.00, date: '2024-10-28', items: ['AWS Certified Cloud Practitioner Exam'] },
            createdAt: new Date('2024-10-29').toISOString(),
        },
        {
            employeeId: 11,
            companyId: 3,
            amount: 850.00,
            currency: 'GBP',
            convertedAmount: 1062.50,
            category: 'Marketing',
            description: 'Tech conference registration and booth setup',
            expenseDate: new Date('2024-11-05').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 10,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_006_conference.pdf',
            ocrData: { vendor: 'TechCrunch Disrupt', total: 850.00, date: '2024-11-05', items: ['Conference registration', 'Exhibition booth'] },
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            employeeId: 12,
            companyId: 3,
            amount: 125.40,
            currency: 'GBP',
            convertedAmount: 156.75,
            category: 'Meals',
            description: 'Client dinner at Gordon Ramsay restaurant',
            expenseDate: new Date('2024-11-22').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 10,
            currentApprovalStep: 1,
            receiptUrl: null,
            ocrData: null,
            createdAt: new Date('2024-11-23').toISOString(),
        },
        {
            employeeId: 13,
            companyId: 3,
            amount: 75.80,
            currency: 'GBP',
            convertedAmount: 94.75,
            category: 'Transportation',
            description: 'Uber rides for client meetings across London',
            expenseDate: new Date('2024-11-14').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 10,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_008_uber_rides.jpg',
            ocrData: { vendor: 'Uber', total: 75.80, date: '2024-11-14', items: ['3 rides in London'] },
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            employeeId: 15,
            companyId: 4,
            amount: 4500.00,
            currency: 'JPY',
            convertedAmount: 30.15,
            category: 'Travel',
            description: 'Hotel accommodation in Tokyo for 3 nights',
            expenseDate: new Date('2024-10-18').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 14,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_009_hotel_tokyo.pdf',
            ocrData: { vendor: 'Hotel Okura Tokyo', total: 4500.00, date: '2024-10-18', items: ['3 nights accommodation'] },
            createdAt: new Date('2024-10-19').toISOString(),
        },
        {
            employeeId: 16,
            companyId: 4,
            amount: 12500.00,
            currency: 'JPY',
            convertedAmount: 83.75,
            category: 'Office Supplies',
            description: 'Software license renewal for design tools',
            expenseDate: new Date('2024-11-01').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 14,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_010_adobe_license.pdf',
            ocrData: { vendor: 'Adobe Systems', total: 12500.00, date: '2024-11-01', items: ['Creative Cloud Annual License'] },
            createdAt: new Date('2024-11-02').toISOString(),
        },
        {
            employeeId: 3,
            companyId: 1,
            amount: 185.25,
            currency: 'USD',
            convertedAmount: 185.25,
            category: 'Marketing',
            description: 'LinkedIn Premium and advertising campaign',
            expenseDate: new Date('2024-11-10').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 2,
            currentApprovalStep: 1,
            receiptUrl: null,
            ocrData: null,
            createdAt: new Date('2024-11-11').toISOString(),
        },
        {
            employeeId: 8,
            companyId: 2,
            amount: 450.00,
            currency: 'EUR',
            convertedAmount: 490.05,
            category: 'Training',
            description: 'React.js advanced workshop and materials',
            expenseDate: new Date('2024-11-08').toISOString().split('T')[0],
            status: 'pending',
            currentApproverId: 7,
            currentApprovalStep: 1,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_012_react_workshop.pdf',
            ocrData: { vendor: 'Frontend Masters', total: 450.00, date: '2024-11-08', items: ['React Advanced Workshop', 'Course Materials'] },
            createdAt: new Date('2024-11-09').toISOString(),
        },

        // Approved expenses (8 total)
        {
            employeeId: 4,
            companyId: 1,
            amount: 320.50,
            currency: 'USD',
            convertedAmount: 320.50,
            category: 'Travel',
            description: 'Hotel stay for Boston conference',
            expenseDate: new Date('2024-10-15').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_013_hotel_boston.pdf',
            ocrData: { vendor: 'Marriott Boston', total: 320.50, date: '2024-10-15', items: ['2 nights accommodation'] },
            createdAt: new Date('2024-10-16').toISOString(),
        },
        {
            employeeId: 5,
            companyId: 1,
            amount: 95.75,
            currency: 'USD',
            convertedAmount: 95.75,
            category: 'Meals',
            description: 'Business dinner with potential client',
            expenseDate: new Date('2024-10-20').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_014_client_dinner.jpg',
            ocrData: { vendor: 'The Capital Grille', total: 95.75, date: '2024-10-20', items: ['Dinner for 2'] },
            createdAt: new Date('2024-10-21').toISOString(),
        },
        {
            employeeId: 9,
            companyId: 2,
            amount: 156.30,
            currency: 'EUR',
            convertedAmount: 170.23,
            category: 'Office Supplies',
            description: 'Ergonomic desk chair and accessories',
            expenseDate: new Date('2024-09-25').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_015_office_chair.pdf',
            ocrData: { vendor: 'IKEA Business', total: 156.30, date: '2024-09-25', items: ['Ergonomic office chair', 'Desk pad'] },
            createdAt: new Date('2024-09-26').toISOString(),
        },
        {
            employeeId: 11,
            companyId: 3,
            amount: 45.20,
            currency: 'GBP',
            convertedAmount: 56.50,
            category: 'Transportation',
            description: 'Train tickets for Manchester office visit',
            expenseDate: new Date('2024-10-05').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_016_train_tickets.jpg',
            ocrData: { vendor: 'Virgin Trains', total: 45.20, date: '2024-10-05', items: ['London to Manchester return'] },
            createdAt: new Date('2024-10-06').toISOString(),
        },
        {
            employeeId: 13,
            companyId: 3,
            amount: 275.00,
            currency: 'GBP',
            convertedAmount: 343.75,
            category: 'Training',
            description: 'Project Management Professional certification',
            expenseDate: new Date('2024-09-15').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_017_pmp_cert.pdf',
            ocrData: { vendor: 'PMI', total: 275.00, date: '2024-09-15', items: ['PMP Certification Exam'] },
            createdAt: new Date('2024-09-16').toISOString(),
        },
        {
            employeeId: 15,
            companyId: 4,
            amount: 8500.00,
            currency: 'JPY',
            convertedAmount: 56.95,
            category: 'Meals',
            description: 'Team building dinner at high-end restaurant',
            expenseDate: new Date('2024-10-12').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_018_team_dinner.jpg',
            ocrData: { vendor: 'Sukiyabashi Jiro', total: 8500.00, date: '2024-10-12', items: ['Team dinner for 5'] },
            createdAt: new Date('2024-10-13').toISOString(),
        },
        {
            employeeId: 16,
            companyId: 4,
            amount: 25000.00,
            currency: 'JPY',
            convertedAmount: 167.50,
            category: 'Marketing',
            description: 'Trade show booth rental and setup',
            expenseDate: new Date('2024-09-28').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_019_trade_show.pdf',
            ocrData: { vendor: 'Tokyo Big Sight', total: 25000.00, date: '2024-09-28', items: ['Booth rental', 'Setup services'] },
            createdAt: new Date('2024-09-29').toISOString(),
        },
        {
            employeeId: 12,
            companyId: 3,
            amount: 89.90,
            currency: 'GBP',
            convertedAmount: 112.38,
            category: 'Office Supplies',
            description: 'External monitor and USB-C hub',
            expenseDate: new Date('2024-10-08').toISOString().split('T')[0],
            status: 'approved',
            currentApproverId: null,
            currentApprovalStep: 2,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_020_monitor.pdf',
            ocrData: { vendor: 'Currys PC World', total: 89.90, date: '2024-10-08', items: ['24" Monitor', 'USB-C Hub'] },
            createdAt: new Date('2024-10-09').toISOString(),
        },

        // Rejected expenses (5 total)
        {
            employeeId: 3,
            companyId: 1,
            amount: 450.00,
            currency: 'USD',
            convertedAmount: 450.00,
            category: 'Meals',
            description: 'Expensive dinner at luxury restaurant',
            expenseDate: new Date('2024-10-25').toISOString().split('T')[0],
            status: 'rejected',
            currentApproverId: null,
            currentApprovalStep: 0,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_021_luxury_dinner.jpg',
            ocrData: { vendor: 'Le Bernardin', total: 450.00, date: '2024-10-25', items: ['Tasting menu for 1'] },
            createdAt: new Date('2024-10-26').toISOString(),
        },
        {
            employeeId: 8,
            companyId: 2,
            amount: 1200.00,
            currency: 'EUR',
            convertedAmount: 1306.80,
            category: 'Travel',
            description: 'First class flight upgrade',
            expenseDate: new Date('2024-09-18').toISOString().split('T')[0],
            status: 'rejected',
            currentApproverId: null,
            currentApprovalStep: 0,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_022_first_class.pdf',
            ocrData: { vendor: 'Lufthansa', total: 1200.00, date: '2024-09-18', items: ['First class upgrade fee'] },
            createdAt: new Date('2024-09-19').toISOString(),
        },
        {
            employeeId: 11,
            companyId: 3,
            amount: 350.00,
            currency: 'GBP',
            convertedAmount: 437.50,
            category: 'Office Supplies',
            description: 'Gaming chair for personal use',
            expenseDate: new Date('2024-10-30').toISOString().split('T')[0],
            status: 'rejected',
            currentApproverId: null,
            currentApprovalStep: 0,
            receiptUrl: null,
            ocrData: null,
            createdAt: new Date('2024-10-31').toISOString(),
        },
        {
            employeeId: 15,
            companyId: 4,
            amount: 15000.00,
            currency: 'JPY',
            convertedAmount: 100.50,
            category: 'Transportation',
            description: 'Personal vacation taxi rides',
            expenseDate: new Date('2024-09-22').toISOString().split('T')[0],
            status: 'rejected',
            currentApproverId: null,
            currentApprovalStep: 0,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_024_personal_taxi.jpg',
            ocrData: { vendor: 'Tokyo Taxi', total: 15000.00, date: '2024-09-22', items: ['Multiple personal rides'] },
            createdAt: new Date('2024-09-23').toISOString(),
        },
        {
            employeeId: 9,
            companyId: 2,
            amount: 899.99,
            currency: 'EUR',
            convertedAmount: 980.99,
            category: 'Training',
            description: 'Unrelated photography course',
            expenseDate: new Date('2024-10-02').toISOString().split('T')[0],
            status: 'rejected',
            currentApproverId: null,
            currentApprovalStep: 0,
            receiptUrl: 'https://receipts-bucket.s3.amazonaws.com/receipts/exp_025_photography.pdf',
            ocrData: { vendor: 'Photography Academy', total: 899.99, date: '2024-10-02', items: ['Advanced Photography Workshop'] },
            createdAt: new Date('2024-10-03').toISOString(),
        }
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});